# Unique name for this workflow
name: Deploy to PreProd on merge

# Definition when the workflow should run
on:
  # The workflow will run whenever an event happens on a pull request
  pull_request:
    types: [closed]

    branches: [PreProd]

    paths:
      - "force-app/**"

jobs:
  deploy-on-UAT-org-on-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }} && github.event.pull_request.merged == true
    steps:
      # Now we install nodejs in the VM, and specify version 14
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Now Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir ~/sf
          tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
          echo "$HOME/sf/bin" >> $GITHUB_PATH
          ~/sf/bin/sf version

      - name: "Installing sfdx git delta"
        run: |
          echo y | sf plugins:install sfdx-git-delta
          sf plugins

      # Install java as it is required for the next step
      - name: "Installing java"
        run: |
          sudo apt-get update
          sudo apt install default-jdk

      # Install SFDX scanner
      - name: "Installing SFDX scanner"
        run: sf plugins:install @salesforce/sfdx-scanner

      - name: "Populate auth file with SFDX_URL secret of integration org"
        shell: bash
        run: |
          echo ${{ secrets.SFDX_PREPROD_INTEGRATION_URL}} > ./SFDX_PREPROD_INTEGRATION_URL.txt

      # Authenticate to org using the URL stored in the text file
      - name: "Authenticate to Integration Org"
        run: sf org login sfdx-url -f ./SFDX_PREPROD_INTEGRATION_URL.txt -s -a integration

      - name: "Create delta packages for neW or modified metadata"
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

      - name: "Deploy delta changes (if any)"
        run: sf project deploy start --source-dir "changed-sources/force-app" --test-level NoTestRun
