# Unique name for this workflow
name: Validate UAT on pull request

# Definition when the workflow should run
on:
  # The workflow will run whenever an event happens on a pull request
  pull_request:
    types: [opened,synchronize]

    branches: [UAT]

    paths:
      - "force-app/**"

jobs:
  validate-deployment-on-UAT-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Now we install nodejs in the VM, and specify version 20
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Read PR Body"
        env:
          # The pull request body is available through the github context object
          # we put the body of the pull request in an env variable (only available to this step)
          PR_BODY: ${{github.event.pull_request.body}}

        run: |
          echo $PR_BODY > ./pr_body.txt
          node ./parsePR.js              
          TESTS=$(cat testsToRun.txt)       
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV

      # Now Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir ~/sf
          tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
          echo "$HOME/sf/bin" >> $GITHUB_PATH
          ~/sf/bin/sf version

      - name: "Installing sfdx git delta"
        run: |
          echo y | sf plugins:install sfdx-git-delta
          sf plugins

      # Install java as it is required for the next step
      - name: "Installing java"
        run: |
          sudo apt-get update
          sudo apt install default-jdk

      # Install SFDX scanner
      - name: "Installing SFDX scanner"
        run: sf plugins:install @salesforce/sfdx-scanner

      - name: "Populate auth file with SFDX_URL secret of integration org"
        shell: bash
        run: |
          echo ${{ secrets.SFDX_UAT_INTEGRATION_URL}} > ./SFDX_UAT_INTEGRATION_URL.txt

      # Authenticate to org using the URL stored in the text file
      - name: "Authenticate to Integration Org"
        run: sf org login sfdx-url -f ./SFDX_UAT_INTEGRATION_URL.txt -s -a integration

      - name: "Create delta packages for new or modified metadata"
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

      - name: "Validate delta changes (if any)"
        if: ${{ env.APEX_TESTS != 'none' }}
        run: |
          echo ${{env.APEX_TESTS}}
          sf project deploy start --source-dir "changed-sources/force-app" --dry-run --test-level RunSpecifiedTests --tests ${{env.APEX_TESTS}} --json

      # If the env variable equals all, we run all tests
      - name: "Validate delta changes - run all tests"
        if: ${{ env.APEX_TESTS == 'none' }}
        run: |
          sf project deploy start --source-dir "changed-sources/force-app" --dry-run --test-level NoTestRun --json
